version: "3.8"

services:
  reino-perdido-backend:
    container_name: reino-perdido-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: reino-perdido-backend #Seeting the image name to reuse in scheduler and queue
    ports:
      - "3001:3000"
      - "7001:7001"
    volumes:
      - .:/usr/src/app

  reino-perdido-db:
    container_name: reino-perdido-db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes: 
      - reino-perdido-volume:/var/lib/postgresql/data
  
volumes:
  reino-perdido-volume:
    driver: local