version: "3.8"

services:
  reino-perdido-backend:
    container_name: reino-perdido-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: reino-perdido-backend #Seeting the image name to reuse in scheduler and queue
    ports:
      - "3001:3000"
      - "7001:7001"
    volumes:
      - .:/usr/src/app